import {
  Settings,
  Upload,
  Check,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Search,
  Plus,
  Minus,
  X,
  Menu,
  User,
  LogOut,
  Edit,
  Trash,
  Copy,
  Download,
  ExternalLink,
  RefreshCw,
  AlertCircle,
  CheckCircle,
  XCircle,
  Info,
  FileText,
  Folder,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  MoreHorizontal,
  MoreVertical,
  Calendar,
  Clock,
  Star,
  Heart,
  Bookmark,
  Mail,
  Link,
  Share,
  Filter,
  Grid,
  List,
  Table,
  Image,
  Video,
  Music,
  File,
  Archive,
  Inbox,
  Send,
  Save,
  Home,
  Flag,
  Bell,
  Tag,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Map,
  MapPin,
  Compass,
  Camera,
  Mic,
  Phone,
  MessageCircle,
  MessageSquare,
  PenTool,
  Scissors,
  Layers,
  Box,
  Package,
  Activity,
  Zap,
  Cloud,
  CloudOff,
  Database,
  Server,
  Monitor,
  Tablet,
  Smartphone,
  Wifi,
  WifiOff,
  Bluetooth,
  Battery,
  Power,
  Sun,
  Moon,
  Sunrise,
  Sunset,
  Thermometer,
  Umbrella,
  Wind,
  Loader,
  Loader2,
  RotateCw,
  RotateCcw,
  Move,
  Maximize,
  Minimize,
  Play,
  Pause,
  FastForward,
  Rewind,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Mic2,
  MicOff,
  Headphones,
  Radio,
  Tv,
  Cast,
  Printer,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Gift,
  Coffee,
  Pizza,
  Truck,
  Wrench,
  Settings2,
  Terminal,
  Code,
  GitBranch,
  Github,
  Gitlab,
  Twitter,
  Facebook,
  Instagram,
  Linkedin,
  Youtube,
  Twitch,
  Slack,
  Chrome,
  FileIcon
} from "lucide-react"

export const Icons = {
  settings: Settings,
  upload: Upload,
  check: Check,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  search: Search,
  plus: Plus,
  minus: Minus,
  close: X,
  menu: Menu,
  user: User,
  logOut: LogOut,
  edit: Edit,
  delete: Trash,
  copy: Copy,
  download: Download,
  external: ExternalLink,
  refresh: RefreshCw,
  warning: AlertCircle,
  success: CheckCircle,
  error: XCircle,
  info: Info,
  file: FileText,
  folder: Folder,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  calendar: Calendar,
  clock: Clock,
  star: Star,
  heart: Heart,
  bookmark: Bookmark,
  mail: Mail,
  link: Link,
  share: Share,
  filter: Filter,
  grid: Grid,
  list: List,
  table: Table,
  image: Image,
  video: Video,
  music: Music,
  archive: Archive,
  inbox: Inbox,
  send: Send,
  save: Save,
  home: Home,
  flag: Flag,
  bell: Bell,
  tag: Tag,
  lock: Lock,
  unlock: Unlock,
  eye: Eye,
  eyeOff: EyeOff,
  map: Map,
  mapPin: MapPin,
  compass: Compass,
  camera: Camera,
  mic: Mic,
  phone: Phone,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
  pen: PenTool,
  scissors: Scissors,
  layers: Layers,
  box: Box,
  package: Package,
  activity: Activity,
  zap: Zap,
  cloud: Cloud,
  cloudOff: CloudOff,
  database: Database,
  server: Server,
  monitor: Monitor,
  tablet: Tablet,
  smartphone: Smartphone,
  wifi: Wifi,
  wifiOff: WifiOff,
  bluetooth: Bluetooth,
  battery: Battery,
  power: Power,
  sun: Sun,
  moon: Moon,
  sunrise: Sunrise,
  sunset: Sunset,
  thermometer: Thermometer,
  umbrella: Umbrella,
  wind: Wind,
  loader: Loader,
  loader2: Loader2,
  rotateCw: RotateCw,
  rotateCcw: RotateCcw,
  move: Move,
  maximize: Maximize,
  minimize: Minimize,
  play: Play,
  pause: Pause,
  fastForward: FastForward,
  rewind: Rewind,
  volume: Volume,
  volume1: Volume1,
  volume2: Volume2,
  volumeX: VolumeX,
  mic2: Mic2,
  micOff: MicOff,
  headphones: Headphones,
  radio: Radio,
  tv: Tv,
  cast: Cast,
  printer: Printer,
  shoppingCart: ShoppingCart,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  gift: Gift,
  coffee: Coffee,
  pizza: Pizza,
  truck: Truck,
  wrench: Wrench,
  settings2: Settings2,
  terminal: Terminal,
  code: Code,
  gitBranch: GitBranch,
  github: Github,
  gitlab: Gitlab,
  twitter: Twitter,
  facebook: Facebook,
  instagram: Instagram,
  linkedin: Linkedin,
  youtube: Youtube,
  twitch: Twitch,
  slack: Slack,
  chrome: Chrome,
  spinner: Loader2,  // Add spinner alias for Loader2
  template: FileIcon  // Add template alias for FileIcon
}
